import Head from "next/head"
import Link from "next/link"
import LayoutInfo from "../../components/layout_info"


export default function Manual(providers) {
    return(
        <LayoutInfo>
          <div className="z-auto">
            <Head>
              <title>EasyCar</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head> 
          </div>

          <div className="grid grid-cols-2 p-52">

          </div>
        </LayoutInfo>
    )
}