import { getProviders, getSession, signOut, useSession } from "next-auth/react";
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import Carousel from "../components/carousel"
import styles from '../styles/Home.module.css'
import LayoutHome from "../components/layout_home"


export default function Home(providers) {
  return (          
    <LayoutHome>
      <div className="z-auto">
        <Head>
          <title>EasyCar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>     
      </div>
    </LayoutHome>
  )


}
