import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rent a Vehicle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a RentCar
        </h1>

        <p className={styles.description}>
          
        </p>

        <div className={styles.grid}>
          
        <Link href="/Sesion/login">
          <a  className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Inicia Sesión en la aplicación.</p>
          </a>
        </Link>    
          
            
        <Link  href="/Sesion/signup">
          <a className={styles.card}>
            <h2>Sign Up &rarr;</h2>
            <p>Registrate en la aplicación.</p>
          </a>
        </Link>

        
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.udistrital.edu.co/inicio"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/images/Escudo_UD.png' alt="Escudo Distrital" width={50} height={50} />
          </span>
        </a>
      </footer>
    </div>
  )
}
