import Head from "next/head"
import Link from "next/link"
import LayoutHome from "../components/layout_home"

export default function Home(providers) {
  return (          
    <LayoutHome>
      <div className="z-auto">
        <Head>
          <title>EasyCar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>     
        <div className="grid grid-cols-2 p-52">
          
          <Link href="info/manual">
              <div className="col-span-2">
                <h2 className="text-7xl italic text-[#e8b984]">Manual de Solicitud</h2>
                
                <div className="flex justify-center m-10 cursor-pointer">
                    <div className="flex flex-col min-w-fit min-h-fit max-w-lg md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg ring-2 ring-[#d3f5e6] hover:scale-110 transition duration-150 ease-in-out">
                      <img className=" w-full h-96 md:h-auto object-cover md:w-48 md:rounded-none md:rounded-l-lg" src="/images/manual.jpg" alt="img" />
                      <div className="p-6 flex flex-col justify-start">
                        <h5 className="text-gray-900 text-xl font-medium mb-2">Paso a Paso</h5>
                        <p className="text-gray-700 text-base mb-4">
                          Entra, enterate de como solicitar un vehículo para tu dia a dia o cualquier otro momento que permita transportarte a ti 
                          y a tu familia o amigos con comodidad y tranquilidad a un comodo precio.
                        </p>
                        <p className="text-gray-600 text-xs"> </p>
                      </div>
                    </div>
                  
                </div>
              </div>
                        
          </Link>
          <Link href="/">
            <div className="col-span-2">
              <h2 className="text-7xl italic text-[#e8b984]">Vehículos Asegurados</h2>
              <div className="flex justify-center m-10 cursor-pointer">
                <div className="flex flex-col min-w-fit min-h-fit max-w-lg md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg ring-2 ring-[#d3f5e6] hover:scale-110 transition duration-150 ease-in-out">
                  <img className=" w-full h-96 md:h-auto object-cover md:w-48 md:rounded-none md:rounded-l-lg" src="/images/seguro.jpeg" alt="img"/>
                  <div className="p-6 flex flex-col justify-start">
                    <h5 className="text-gray-900 text-xl font-medium mb-2">Viaja Seguro</h5>
                    <p className="text-gray-700 text-base mb-4">
                      Nuestros Vehículos cuentan con un seguro contra robos y accidentes, que establecen un estandar de seguridad para nuestros vehículos y usuarios, por esto 
                      y mucho mas puedes viajar tranquilo con los vehículos que se ofrecen en la plataforma.
                    </p>
                    <p className="text-gray-600 text-xs"> Aplica Condiciones y Restricciones</p>
                  </div>
                </div>
              </div>
            </div>
          </Link>
               
        </div>       
      </div>
    </LayoutHome>
  )


}
